### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by Sevelar** [Sevelar/DisViewer#11]
## List of things to do:
- [ ] #10 [ ! ]
- [ ] Add the About Page (inside Help button; information about version of the app and author) [ ! ]
- [ ] #14 [ ! ]
- [ ] Add the User Edit page (options to change username, about me and avatar) [ ! ]
- [ ] Add functionality to Markdown buttons in Editor section [ ! ]
- [ ] Add styling to converted Markdown tags in Preview section [ ! ]
- [ ] Add functionality to top-level application menu (Electron) [ ! ]
- [ ] Add auto-updating support
- [ ] Add shortcuts support
